### PR TITLE
Refactored javascript functions and added a new function

### PR DESCRIPTION
**Pull request by ashwinexe**
Now the functions `openMyself()` and `closeMyself()` will only do the task of opening and closing on clicking the button, where as `checkScreenWidth() `will be responsible for reacting to screen changes.

### CODE REVIEW

**Comment by Skyhero-admin** [comment]
Is it alright if I merge this ?

**Comment by ashwinexe** [comment]
Yes, go ahead.

**Comment by Skyhero-admin** [comment]
why did you close the PR ?

**Comment by ashwinexe** [comment]
Generally it is merged, but you already made changes (better ones) to your code so there was no need to merge it.

**Comment by Skyhero-admin** [comment]
ohh

**Comment by Skyhero-admin** [comment]
I could have still merged it since you made the actual changes and it would be wrong not to do it

**Comment by ashwinexe** [comment]
okay I'll open a new one

**Pull request closed without merging**
